blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/syalioune/gcp-finops-sentinel/discussions
    about: For general discussions, ideas, and community Q&A
  - name: Documentation
    url: https://github.com/syalioune/gcp-finops-sentinel/blob/main/README.md
    about: Read the full documentation before opening an issue
  - name: Security Vulnerability
    url: https://github.com/syalioune/gcp-finops-sentinel/security/advisories/new
    about: Report security vulnerabilities privately through Security Advisories
